// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://veubsffsobbsdjcqbxjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZldWJzZmZzb2Jic2RqY3FieGprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NTU3NTgsImV4cCI6MjA2OTQzMTc1OH0.yXEaOnvyZgmYWowzfGwmi5w89Eu6H4z_xD-6nB4L7CE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});