// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pctpxnobnbkkgbisxxci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjdHB4bm9ibmJra2diaXN4eGNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNzg4NTgsImV4cCI6MjA2OTk1NDg1OH0.Vr2exj4N1BkSNZ0M2IUvCaRZeKJPJxzmZ3Wn17Z9yqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});